-- AlterTable
ALTER TABLE `peminjaman` ADD COLUMN `bukti_pembayaran` VARCHAR(191) NULL,
    ADD COLUMN `status_bayar` ENUM('MENUNGGU_VERIFIKASI', 'DISETUJUI', 'DITOLAK') NOT NULL DEFAULT 'MENUNGGU_VERIFIKASI';
